workload_path: "../../Workloads/Snowset/workload1h-5m-30s_1.csv"
workload_name: "workload1h-5m-30s_1"
host: ""
databend_port: 
prometheus_port: 
count_limit: 1000
time_limit: 270
use_operator: 1
wait: 8
interval: 30
query: [TPCH,TPCH,TPCH,TPCH,tpcds_all,tpcds_all,imdb,llm]
db: [tpch500m,tpch1g,tpch5g,tpch9g,tpcds1g,tpcds2g,imdb,llm]
op_scale: 100
initial_count: 10